# Generated by Django 2.0.6 on 2018-08-25 20:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_title', models.CharField(max_length=30)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_title', models.CharField(max_length=30)),
                ('pro_desc', models.TextField(max_length=300)),
                ('pro_pic', models.FileField(blank=True, default='pro_pics/Dummy_projekt.png', upload_to='pro_pics')),
                ('pro_complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=50)),
                ('task_explain', models.CharField(max_length=1500)),
                ('task_imp', models.IntegerField(default=0)),
                ('task_dead', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('task_eff', models.FloatField(default=1.0)),
                ('complete', models.BooleanField(default=False)),
                ('task_start', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('id_field', models.CharField(default='id_field', max_length=8)),
                ('task_end', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('shifted', models.BooleanField(default=False)),
                ('shift_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Project')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.DateTimeField(default=datetime.datetime(2018, 8, 25, 22, 40, 4, 600307))),
                ('promotion', models.IntegerField(default=0)),
                ('feature', models.CharField(max_length=500)),
                ('control', models.IntegerField(default=0)),
                ('like', models.CharField(max_length=500)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textmsg', models.CharField(max_length=300)),
                ('post_time', models.DateTimeField(default=datetime.datetime(2018, 8, 25, 22, 40, 4, 600307))),
                ('sender', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Task')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='Deutschland', max_length=11)),
                ('age', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('agree', models.BooleanField(default=False)),
                ('cust_icon', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Task'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
