# Generated by Django 2.0.6 on 2018-08-26 00:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0003_auto_20180825_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.NullBooleanField(default=None)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userfeed',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 26, 2, 14, 57, 948055)),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 26, 2, 14, 57, 945911)),
        ),
    ]
