# Generated by Django 2.0.6 on 2018-09-01 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20180826_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agree2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userfeed',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 1, 20, 21, 37, 148651)),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 1, 20, 21, 37, 148651)),
        ),
    ]
