# Generated by Django 2.0.6 on 2018-10-30 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20181026_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeed',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 30, 16, 40, 30, 310438)),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 30, 16, 40, 30, 309394)),
        ),
    ]
